service: 'aws-ws-request-service'

provider:
  name: aws
  runtime: nodejs16.x
  region: 'eu-central-1'
  architecture: arm64
  timeout: 60
  memorySize: 1024
  deploymentMethod: 'direct'
  versionFunctions: false
  tags:
    app: platform
    env: '${opt:stage}'
  iam:
    role:
      name: '${self:service}-${opt:stage}'
      path: '/lambda-${opt:stage}/'
      statements:
        - Effect: 'Allow'
          Resource:
            - 'arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${env:WS_REQUESTS_DYNAMODB_TABLE}'
          Action:
            - 'dynamodb:DescribeTable'
            - 'dynamodb:Query'
            - 'dynamodb:Scan'
            - 'dynamodb:GetItem'
            - 'dynamodb:PutItem'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
      tags:
        app: praedia
        env: '${opt:stage}'
  environment:
    ENVIRONMENT: '${opt:stage}'
    WS_REQUESTS_DYNAMODB_TABLE: '${env:WS_REQUESTS_DYNAMODB_TABLE}'
    NO_COLOR: true
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

plugins:
  - serverless-offline
  - serverless-webpack

functions:
  entrypoint:
    handler: src/index.handler

custom:
  webpack:
    webpackConfig: 'webpack.config.js' # Name of webpack configuration file
    includeModules: true # Node modules configuration for packaging
    packager: 'npm' # Packager that will be used to package your external modules
